### ISSUE TITLE
Draft helper for human drafts

### ISSUE THREAD

**Issue by Drizzt893** [Razviar/mtgap#122]
This might be a bug or a tournament integrity thing, but the draft overlay no longer works in Traditional Draft.

Could someone enable the tracker to work with the human draft setup?

**Comment by Razviar** [comment]
If you have drafted in human drafts, please get the Player.log file from {USERNAME}\AppData\LocalLow\Wizards Of The Coast\MTGA folder and send it over to me using any cloud service. We need human draft logs samples to see log changes.

**Comment by Drizzt893** [comment]
Will do!  Might be tomorrow.

**Comment by Drizzt893** [comment]
https://drive.google.com/open?id=1MR7FN4Aoq6A9PLRiugaZO9GE6WpkFSYk I think I did that right.  Let me know if you have trouble accessing the file.

**Comment by Razviar** [comment]
@Drizzt893 you probably restarted MTGA after drafting and I don't see info I need. Please zip and send me over logs from C:\Program Files (x86)\Wizards of the Coast\MTGA\MTGA_Data\Logs\Logs with dates which coincide with time of your draft and relatively big size.

**Comment by Drizzt893** [comment]
I don't remember the dates of my drafts and I was busy, so this morning I ran another draft and grabbed the files.  Here's the LocalLow MTGA after drafting then grabbing it before restarting arena:
https://drive.google.com/open?id=1MR7FN4Aoq6A9PLRiugaZO9GE6WpkFSYk

Here's the Program Files (x86) Logs for today 
https://drive.google.com/open?id=1LMak_wzCP9UE_BXaaEy7JVM9Y9BJ0j8z'

Let me know if it's good or you need more!

**Comment by Razviar** [comment]
Thanks for the logs, this time logs are correct. BUT. Unfortunately WOTC doesn't actually log human draft as they promised. Here's what we have:

[UnityCrossThreadLogger]<== Draft.MakeHumanDraftPick {"id":210,"payload":{"IsPickingCompleted":false,"IsPickSuccessful":true,"TableInfo":null,"PickInfo":null,"PackInfo":null}}

So, instead of actual data we have only NULLs instead of tableinfo, pickinfo and packinfo. With such logs we can't actually run draft helper. We will report this issue to WOTC and will keep monitoring this matter.

**Comment by Drizzt893** [comment]
That's annoying.  Thanks for working on it!  You're always on top of things and I really appreciate it.  Most of the time I have an issue, I look it up on here and you're working on it or you've told someone how to fix it.

**Comment by Razviar** [comment]
Please upvote and comment this one: https://feedback.wizards.com/forums/918667-mtg-arena-bugs/suggestions/40198426-draft-logs-broken

**Comment by Drizzt893** [comment]
Done!
