### ISSUE TITLE
Wrong collection progress with 'Boostable' filter

### ISSUE THREAD

**Issue by MaurGi** [Razviar/mtgap#236]
**Detailed context (ISSUES WILL NOT BE INVESIGATED WITHOUT IT!):**
- Link to your MTGA Pro account: Magico#54196
- Link to page/pages are in question https://mtgarena.pro/progress/
- Scr0eenshots of issue if applicable 

![image](https://user-images.githubusercontent.com/13138584/115102352-30f2ce00-9eff-11eb-83fd-b303010fe35a.png)

**Your Desktop:**
 - OS: [e.g. Windows 10] Windows 10
 - App type: Standalone or Overwolf Standalone
 - App Version [e.g. 2.0.22] 2.1.24
00
**Describe the bug**

As Strixhaven launched it lost months of my collection progress, I played every day since Feb and I had 100% single collection and 92.5 % of all cards, but all my history is now gone, the account chart has info on 2/1 and then 4/14, everything else is gone.
I used this tracker because I like to collect the cards and seing the progress was my motivation, now that the history is gone, I will move to another tracker.

**To Reproduce**
1. Go to '...' Progress
2. It's gone
3. cry....

**Comment by Razviar** [comment]
Hello. Your collection is in place, you can see it for yourself if you switch booster from 'Boostable' to 'Craftable' or 'All Cards' (see screnshot).
![image](https://user-images.githubusercontent.com/29640542/115102798-0c761080-9f56-11eb-9cac-75a0b81183a5.png)

We will investigate why "Boostable" filter is showing wrong numbers. 

Also, I would recommend you to skip in future that 'I will move to another tracker' part of your bug report, since it's not adding any useful information to bug report, it's your decision and you don't need to inform us about your official departure to another tracker. Thanks.

**Comment by Razviar** [comment]
Your progress is fixed now, thanks for reporting. To see the change please use ctrl+f5
