### ISSUE TITLE
Updates Not Showing On Website

### ISSUE THREAD

**Issue by TXSoulja** [Razviar/mtgap#7]
I can see the tracker pulling updates from the logs, but when I go to my profile on the website, noting new appears.

**Comment by Razviar** [comment]
Please provide your mtgapro nickname, mtga id and screenshot of the tracker

**Comment by ehearn** [comment]
I'm experiencing a similar problem. The Matches section is updating but none of my Deck W/L values have updated since the 21st. Also none of my matches from the 22nd and all but 1 from the 21st are listed in the Matches section. I did just update to 2.0.10 yesterday which is when the matches started showing up again, but not everything has.

I've tried manually re-syncing the log but that didn't seem to help.

My MTGAP nickname is Argentus, my MTGA id is Argentus#06124. Attached are two screenshots of the tracker.

![MTGAP 2019-11-24 090619](https://user-images.githubusercontent.com/7007138/69497486-bbfe9e80-0e9a-11ea-8a10-880a3c66d6a8.png)
![MTGAP Accounts 2019-11-24 090753](https://user-images.githubusercontent.com/7007138/69497487-bbfe9e80-0e9a-11ea-922d-08510dc86f5b.png)

**Comment by Razviar** [comment]
Try 2.0.11 version, just released.

**Comment by p2dr** [comment]
i have this same issue, most of time its collection not updating properly or opened boosters not showing up, seems even worse on 2.0.11

Pando0
Pando0#74049

![tracker](https://user-images.githubusercontent.com/58152002/69502805-a37e9a80-0f13-11ea-8d73-f11101724524.png)

**Comment by ehearn** [comment]
Excellent, thank you. 2.0.11 has resolved the issues I've noticed so far.

**Comment by Razviar** [comment]
v.2.0.12 should be more reliable. Closing this for now, but we'll keep monitoring.
